-- DDL generated by Postico 1.5.20
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE events (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    description text,
    event_date timestamp with time zone,
    date_added timestamp with time zone DEFAULT '2022-06-19 17:01:56.664269+00'::timestamp with time zone,
    blob text,
    category text,
    priority integer
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX events_pkey ON events(id int4_ops);
